layout: page
title: "Chitmeo's blog"
description: Personal blog
theme: jekyll-theme-minimal
baseurl: ""
domain: chitmeo.com
url: https://chitmeo.com
email: kyle@chitmeo.com
github_username: chitmeo
markdown: kramdown
