layout: default
title: "Chitmeo"
description: Personal blog
theme: minima
baseurl: ""
domain: chitmeo.com
url: https://chitmeo.com
email: kyle@chitmeo.com
github_username: chitmeo
markdown: kramdown
plugins: 
  - jekyll-feed
  - jekyll-seo-tag
google_analytics: UA-168736414-1