layout: default
title: "Chitmeo's blog"
description: Personal blog
theme: jekyll-theme-architect
baseurl: ""
domain: chitmeo.com
url: https://chitmeo.com
email: kyle@chitmeo.com
github_username: chitmeo
markdown: kramdown
plugins: 
  - jekyll-feed
  - jekyll-seo-tag