layout: page
title: "Chitmeo's blog"
description: Personal blog
theme: minima
baseurl: ""
domain: chitmeo.com
url: https://chitmeo.com
email: kyle@chitmeo.com
github_username: chitmeo
markdown: kramdown
permalink: /:categories/:year/:month/:day/:title:output_ext